name: mongo_db_driver
version: 1.0.0-1.0.dev
description: MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more!
homepage: https://github.com/mongo-dart/mongo_db_driver
funding:
  - https://www.paypal.com/donate?hosted_button_id=YRUNF9YWKX2NW
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bson: ^5.0.0
  crypto: ^3.0.0
  logging: ^1.0.0
  mongo_db_query: ^0.1.0-1.0.dev
   # path: ../mongo_db_query
  collection: ^1.15.0
  path: ^1.8.0
  pool: ^1.5.0
  basic_utils: ^5.2.0 
  decimal: ^2.3.3
  uuid: ^4.1.0
  sasl_scram: ^0.1.0
  vy_string_utils: ^0.4.0
  meta: ^1.8.0
  fixnum: ^1.0.1
    
dev_dependencies:
  test: ^1.16.4
  lints: ^4.0.0

false_secrets:
 - /test/certificates_for_testing/*.key
 - /test/certificates_for_testing/*.pem
